### ISSUE TITLE
Running test script sometimes produces an error

### ISSUE THREAD

**Issue by SobakaSlava** [paralect/koa-api-starter#65]
```
flowplant-test-api       |   "stack": "MongoError: a collection 'api-test.users' already exists\n    at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:261:20)\n    at MessageStream.emit (events.js:311:20)\n    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:42:5)\n    at doWrite (_stream_writable.js:441:12)\n    at writeOrBuffer (_stream_writable.js:425:5)\n    at MessageStream.Writable.write (_stream_writable.js:316:11)\n    at Socket.ondata (_stream_readable.js:714:22)\n    at Socket.emit (events.js:311:20)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:209:10)\n    at TCP.onS
```

this error somitimes appear when running tests. usually when running in CI

**Comment by hovoodd** [comment]
https://github.com/paralect/node-mongo/pull/20/files

**Comment by hovoodd** [comment]
already fixed
